//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheRideYouRent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int ID { get; set; }
        public string CarNo { get; set; }
        public string CarMake { get; set; }
        public string Model { get; set; }
        public string BodyType { get; set; }
        public int KilometresTraveled { get; set; }
        public int ServiceKilometres { get; set; }
        public string Available { get; set; }
        
    }
}
