//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheRideYouRent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelLookup
    {
        public int ModelID { get; set; }
        public string ModelName { get; set; }
        public Nullable<int> CarMakeID { get; set; }
    
        public virtual CarMakeLookup CarMakeLookup { get; set; }
    }
}
