//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheRideYouRent.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ST10085839_CLDV6211_Part2Entities : DbContext
    {
        public ST10085839_CLDV6211_Part2Entities()
            : base("name=ST10085839_CLDV6211_Part2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AvailabilityLookup> AvailabilityLookups { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<CarMakeLookup> CarMakeLookups { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Inspector> Inspectors { get; set; }
        public virtual DbSet<ModelLookup> ModelLookups { get; set; }
        public virtual DbSet<Rental> Rentals { get; set; }
        public virtual DbSet<ReturnID> ReturnIDs { get; set; }
    }
}
