//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheRideYouRent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public string CarNo { get; set; }
        public string DriverID { get; set; }
        public string Inspector_no { get; set; }
        public Nullable<decimal> RentalFee { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int ID { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Inspector Inspector { get; set; }
    }
}
